/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarBadge: typeof import('./components/chat/AvatarBadge.vue')['default']
    ChatStatePanel: typeof import('./components/chat/ChatStatePanel.vue')['default']
    ChatTopbar: typeof import('./components/chat/ChatTopbar.vue')['default']
    ConversationListItem: typeof import('./components/chat/ConversationListItem.vue')['default']
    ConversationProfileDrawer: typeof import('./components/chat/ConversationProfileDrawer.vue')['default']
    ConversationSidebar: typeof import('./components/chat/ConversationSidebar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    MessageBubble: typeof import('./components/chat/MessageBubble.vue')['default']
    MessageComposer: typeof import('./components/chat/MessageComposer.vue')['default']
    MessagePane: typeof import('./components/chat/MessagePane.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
