/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarBadge: typeof import('./components/chat/AvatarBadge.vue')['default']
    CallOverlay: typeof import('./components/chat/CallOverlay.vue')['default']
    ChatStatePanel: typeof import('./components/chat/ChatStatePanel.vue')['default']
    ChatTopbar: typeof import('./components/chat/ChatTopbar.vue')['default']
    ContactsPanel: typeof import('./components/chat/ContactsPanel.vue')['default']
    ConversationListItem: typeof import('./components/chat/ConversationListItem.vue')['default']
    ConversationProfileDrawer: typeof import('./components/chat/ConversationProfileDrawer.vue')['default']
    ConversationProfilePanelBody: typeof import('./components/chat/ConversationProfilePanelBody.vue')['default']
    ConversationSidebar: typeof import('./components/chat/ConversationSidebar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ImageViewer: typeof import('./components/chat/ImageViewer.vue')['default']
    MentionSelector: typeof import('./components/chat/MentionSelector.vue')['default']
    MessageBubble: typeof import('./components/chat/MessageBubble.vue')['default']
    MessageComposer: typeof import('./components/chat/MessageComposer.vue')['default']
    MessagePane: typeof import('./components/chat/MessagePane.vue')['default']
    MessageReadDetails: typeof import('./components/chat/MessageReadDetails.vue')['default']
    PinnedMessagesBanner: typeof import('./components/chat/PinnedMessagesBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduledMessagesPanel: typeof import('./components/chat/ScheduledMessagesPanel.vue')['default']
    VoicePlayer: typeof import('./components/chat/VoicePlayer.vue')['default']
    VoiceRecorder: typeof import('./components/chat/VoiceRecorder.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
